"use strict";
function newGuest(){if(guests.length>=MAX_GUESTS)return;const shirts=[COLORS.pink,COLORS.cyan,"#a96cff","#ffb65c",COLORS.green,"#ff6c7d","#6e8fff"],skins=["#f0c6a2","#dca17d","#b97454","#875039","#6b3f31"],hairs=["#211920","#50352a","#17171d","#7c4a2e","#c5a56d"];const g={x:entrance.x,y:entrance.y,state:"idle",activity:null,path:[],pi:0,speed:1.7+Math.random()*.9,phase:Math.random()*6.28,done:0,max:2+Math.floor(Math.random()*3),happy:.62+Math.random()*.22,shirt:shirts[Math.floor(Math.random()*shirts.length)],skin:skins[Math.floor(Math.random()*skins.length)],hair:hairs[Math.floor(Math.random()*hairs.length)],flip:1};guests.push(g);chooseNext(g)}
function moveTo(g,target,next){const p=pathfind(g,target);g.path=p.length>1?p.slice(1):[];g.pi=0;g.next=next;g.state="move";if(!g.path&&next==="exit")exitGuest(g)}
function chooseNext(g){if(g.done>=g.max)return moveTo(g,entrance,"exit");const a=chooseActivity();if(!a){g.happy-=.12;return moveTo(g,entrance,"exit")}g.activity=a;moveTo(g,a.target,"activity")}
function exitGuest(g){recordGuest(g.happy);guests=guests.filter(x=>x!==g)}
function updateGuests(dt){for(const g of [...guests]){if(g.state==="move"){const t=g.path[g.pi];if(!t){if(g.next==="activity"){g.state="activity";g.timer=0}else exitGuest(g);continue}const dx=t.x-g.x,dy=t.y-g.y,d=Math.hypot(dx,dy);if(d<.045){g.x=t.x;g.y=t.y;g.pi++;continue}g.flip=dx-dy>=0?1:-1;const step=Math.min(d,g.speed*dt);g.x+=dx/d*step;g.y+=dy/d*step}else if(g.state==="activity"){g.timer=(g.timer||0)+dt;if(g.timer>=g.activity.dur){const a=g.activity;g.done++;g.happy=Math.max(.1,Math.min(1,g.happy+(a.quality-.5)*.12));if(a.spend>0)earn(Math.round(a.spend*(.85+state.rep/160)),a.kind==="drink"?4:3);g.activity=null;chooseNext(g)}}}}
function startNight(){if(state.open)return finishNight(true);if(!objects.some(o=>o.kind==="bar")||!objects.some(o=>o.kind==="dance"))return toast("You need at least one bar and one dance floor.");selected=null;bulldoze=false;state.open=true;state.nightIncome=0;state.nightGuests=0;nightLeft=NIGHT_LENGTH;spawnClock=0;closeDrawers();save();renderAll();toast("Doors open. Tonight's crowd is arriving.")}
function finishNight(manual=false){if(!state.open)return;state.open=false;guests.length=0;state.night++;const finishedIncome=state.nightIncome,finishedGuests=state.nightGuests;state.rep=Math.min(100,state.rep+Math.min(2.5,finishedGuests*.05));save();recalcRating();renderAll();showReport(finishedIncome,finishedGuests);toast((manual?"Club closed. ":"Night complete. ")+`Earned $${finishedIncome.toLocaleString()}.`)}
function showReport(income,guestsN){$("#reportIncome").textContent="$"+income.toLocaleString();$("#reportGuests").textContent=guestsN;$("#reportRating").textContent=state.rating.toFixed(1)+"★";$("#report").classList.add("reportOpen");reportOpen=true}
function renderHUD(){const p=progress();$("#level").textContent=state.level;$("#cash").textContent="$"+Math.floor(state.cash).toLocaleString();$("#rep").textContent=Math.round(state.rep)+" REP";$("#rating").textContent=state.rating.toFixed(1)+" ★";$("#xpFill").style.width=(p.ratio*100)+"%";$("#xpText").textContent=state.level>=10?"MAX":Math.floor(p.cur)+" / "+p.total;$("#nightLabel").textContent="NIGHT "+state.night;$("#nightIncome").textContent="$"+Math.floor(state.nightIncome).toLocaleString();$("#nightGuests").textContent=state.nightGuests;$("#clock").textContent=state.open?Math.floor(nightLeft/60)+":"+Math.floor(nightLeft%60).toString().padStart(2,"0"):"BUILD MODE";$("#openBtn").textContent=state.open?"CLOSE CLUB":"OPEN CLUB";$("#openBtn").classList.toggle("open",state.open);$("#bulldoze").disabled=state.open;$("#resetLayout").disabled=state.open}
function renderCats(){const defs=[["bars","▰","Bars"],["seating","▱","Seating"],["dance","◇","Dance"],["walls","▦","Walls"],["decor","✧","Decor"]];$("#cats").innerHTML=defs.map(([id,ic,n])=>`<button class="cat ${category===id?"active":""}" data-cat="${id}"><b>${ic}</b><span>${n}</span></button>`).join("");$$('.cat').forEach(b=>b.onclick=()=>{category=b.dataset.cat;renderCats();renderItems()})}
function renderItems(){const root=$("#items");root.innerHTML="";for(const it of catalog[category]){const locked=it.level>state.level,sel=selected?.id===it.id;const b=document.createElement("button");b.className="item"+(locked?" locked":"")+(sel?" selected":"");b.innerHTML=`<div class="thumb"><b>${it.icon}</b><small>+${it.vibe} VIBE</small></div><strong>${it.name}</strong><div class="meta"><span>Lv. ${it.level}</span><span>${it.cost?"$"+it.cost.toLocaleString():"FREE"}</span></div>${it.cap?`<div class="capacity">Capacity +${it.cap}</div>`:""}${locked?`<span class="lock">LEVEL ${it.level}</span>`:""}`;b.onclick=()=>{if(state.open)return toast("Close the club before building.");if(locked)return toast("Unlocks at level "+it.level+".");if(state.cash<it.cost)return toast("Not enough cash yet.");selected=it;bulldoze=false;$("#bulldoze").classList.remove("active");renderItems();toast(it.kind==="wall"?it.name+" selected — click the club to apply.":it.name+" selected — click the floor to place it.")};root.appendChild(b)}}
function renderGoals(){const root=$("#goals");root.innerHTML="";for(const g of goalDefs){const done=g.test(state),claimed=state.claimed.includes(g.id);const row=document.createElement("div");row.className="goal"+(done?" done":"")+(claimed?" claimed":"");row.innerHTML=`<div><strong>${g.name}</strong><span>${done?"Complete":"In progress"}</span></div><button ${!done||claimed?"disabled":""}>${claimed?"CLAIMED":done?"CLAIM $"+g.reward.toLocaleString():"$"+g.reward.toLocaleString()}</button>`;row.querySelector("button").onclick=()=>{if(!done||claimed)return;state.claimed.push(g.id);state.cash+=g.reward;state.xp+=Math.round(g.reward/12);recalcLevel();save();renderAll();toast("Goal claimed: +$"+g.reward.toLocaleString())};root.appendChild(row)}}
function renderAll(){renderHUD();renderCats();renderItems();renderGoals()}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove("show"),2300)}
function showDrawer(name){$("#designDrawer").classList.toggle("open",name==="design");$("#goalsDrawer").classList.toggle("open",name==="goals");$$('.nav').forEach(b=>b.classList.toggle("active",b.dataset.panel===name||(!name&&b.dataset.panel==="club")))}
function closeDrawers(){showDrawer(null)}
function placeAt(t){if(state.open||!selected)return;if(selected.kind==="wall"){const reward=Math.max(10,Math.round(selected.cost/20));if(!purchase(selected.cost,reward,selected.vibe))return toast("Not enough cash yet.");state.wall=selected.style;selected=null;recalcRating();save();renderAll();toast("Wall theme applied.");return}const [w,h]=selected.fp;if(!canPlace(t.x,t.y,w,h))return toast("That space is blocked.");const item=selected,reward=Math.max(18,Math.round(item.cost/14));if(!purchase(item.cost,reward,item.vibe))return toast("Not enough cash yet.");objects.push({id:item.id+"-"+Date.now(),catalogId:item.id,kind:item.kind,x:t.x,y:t.y,w,h,style:item.style,solid:item.kind!=="dance",vibe:item.vibe,cap:item.cap});selected=null;save();recalcRating();renderAll();toast(item.name+" placed.")}
function bulldozeAt(t){if(state.open)return;const i=objects.findIndex(o=>t.x>=o.x&&t.x<o.x+o.w&&t.y>=o.y&&t.y<o.y+o.h&&o.kind!=="dj");if(i<0)return toast("Nothing removable there.");const o=objects.splice(i,1)[0];state.cash+=Math.max(50,Math.round((o.vibe||5)*9));save();recalcRating();renderAll();toast("Item removed. Partial value returned.")}
