"use strict";
function iso(x,y,z=0){return{x:(x-y)*TILE_W*.5,y:(x+y)*TILE_H*.5-z}}
function uniso(x,y){return{x:y/TILE_H+x/TILE_W,y:y/TILE_H-x/TILE_W}}
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0);draw()}
function origin(){return{x:canvas.clientWidth*.5,y:135}}
function worldToScreen(p){const o=origin();return{x:o.x+view.panX+p.x*view.zoom,y:o.y+view.panY+p.y*view.zoom}}
function screenToWorld(sx,sy){const o=origin();return{x:(sx-o.x-view.panX)/view.zoom,y:(sy-o.y-view.panY)/view.zoom}}
function screenToTile(sx,sy){const w=screenToWorld(sx,sy),t=uniso(w.x,w.y);return{x:Math.floor(t.x),y:Math.floor(t.y)}}
function diamond(x,y,w=1,h=1,z=0){return[iso(x,y,z),iso(x+w,y,z),iso(x+w,y+h,z),iso(x,y+h,z)]}
function path(points,fill,stroke=null,lw=1,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.beginPath();points.forEach((p,i)=>{const s=worldToScreen(p);i?ctx.lineTo(s.x,s.y):ctx.moveTo(s.x,s.y)});ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}ctx.restore()}
function line(a,b,color,lw=2,alpha=1){a=worldToScreen(a);b=worldToScreen(b);ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=color;ctx.lineWidth=lw;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore()}
function ellipse(p,rx,ry,fill,stroke=null,lw=1,alpha=1){p=worldToScreen(p);ctx.save();ctx.globalAlpha=alpha;ctx.beginPath();ctx.ellipse(p.x,p.y,rx*view.zoom,ry*view.zoom,0,0,Math.PI*2);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}ctx.restore()}
function rectScreen(x,y,w,h,fill,stroke=null,r=0){ctx.save();ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,r);else ctx.rect(x,y,w,h);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}ctx.restore()}
function prism(o,height,top,sideA,sideB){const topP=diamond(o.x,o.y,o.w||1,o.h||1,height),base=diamond(o.x,o.y,o.w||1,o.h||1,0);path(topP,top);path([topP[1],base[1],base[2],topP[2]],sideA);path([topP[3],topP[2],base[2],base[3]],sideB)}
function drawRoom(){for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++)path(diamond(x,y),((x+y)%2?COLORS.floorB:COLORS.floorA),COLORS.grid,1);path(diamond(0,0,GRID_W,GRID_H),null,"rgba(140,92,255,.25)",3);const c=iso(0,0),r=iso(GRID_W,0),l=iso(0,GRID_H),H=132,themes={charcoal:["#211e31","#171522",COLORS.purple,COLORS.cyan],violet:["#30203e","#22172f",COLORS.pink,COLORS.purple],midnight:["#142a40","#101d31",COLORS.cyan,"#4d7bff"],luxury:["#31251f","#241c1a",COLORS.gold,"#d49b63"]},t=themes[state.wall]||themes.charcoal;path([c,r,{x:r.x,y:r.y-H},{x:c.x,y:c.y-H}],t[0]);path([c,l,{x:l.x,y:l.y-H},{x:c.x,y:c.y-H}],t[1]);line({x:c.x,y:c.y-H},{x:r.x,y:r.y-H},t[2],3,.5);line({x:c.x,y:c.y-H},{x:l.x,y:l.y-H},t[3],3,.45);for(let x=1;x<GRID_W;x+=3){const p=iso(x,0);line({x:p.x,y:p.y-8},{x:p.x,y:p.y-H+10},t[2],1,.22)}const sign=worldToScreen(iso(7.5,0,82));rectScreen(sign.x-49*view.zoom,sign.y-15*view.zoom,98*view.zoom,30*view.zoom,"rgba(7,6,16,.9)",t[2],9*view.zoom);ctx.save();ctx.fillStyle="#f3edff";ctx.font=`${11*view.zoom}px system-ui`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("NIGHTCLUB",sign.x,sign.y);ctx.restore();const e=worldToScreen(iso(entrance.x,entrance.y));ctx.save();ctx.fillStyle="rgba(5,5,10,.75)";ctx.beginPath();ctx.ellipse(e.x,e.y+7*view.zoom,38*view.zoom,12*view.zoom,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=COLORS.cyan;ctx.globalAlpha=.7;ctx.lineWidth=2;ctx.stroke();ctx.restore()}
function drawDance(o,time){const pals={starter:["#5d36d8","#a638d8","#235dd8","#18a8c0"],pulse:[COLORS.pink,COLORS.purple,COLORS.cyan,"#5d36d8"],laser:["#19d8c6","#1f5bea","#bf45ff",COLORS.pink],prism:[COLORS.pink,COLORS.gold,COLORS.cyan,COLORS.purple]},pal=pals[o.style]||pals.starter,pulse=.72+.18*Math.sin(time*.003);for(let yy=0;yy<o.h;yy++)for(let xx=0;xx<o.w;xx++)path(diamond(o.x+xx,o.y+yy,1,1,2),pal[(xx+yy)%pal.length],"rgba(255,255,255,.1)",1,pulse)}
function drawBar(o){const th={starter:["#3c3449","#181523","#252035",COLORS.cyan],neon:["#52307d","#211536","#342047",COLORS.pink],lounge:["#4b3b63","#1d1929","#30263f","#9a6cff"],glow:["#6c3878","#24162d","#3b2145",COLORS.cyan],vip:["#785838","#251d1b","#3f2d25",COLORS.gold]}[o.style]||["#3c3449","#181523","#252035",COLORS.cyan];prism(o,38,th[0],th[1],th[2]);line(iso(o.x+.1,o.y+o.h,24),iso(o.x+o.w-.1,o.y+o.h,24),th[3],4,.9);const shelf={...o,y:o.y-.03,h:.28};prism(shelf,68,"#282333","#12101a","#1a1723");line(iso(o.x+.1,o.y+.25,50),iso(o.x+o.w-.1,o.y+.25,50),th[3],2,.75);const colors=[COLORS.cyan,"#ffaf40",COLORS.pink,"#68e58d","#a76cff"];for(let i=0;i<Math.max(3,o.w*2);i++){const p=iso(o.x+o.w*(i+.7)/Math.max(3,o.w*2),o.y+.08,46);const s=worldToScreen(p);ctx.save();ctx.fillStyle=colors[i%colors.length];ctx.globalAlpha=.9;ctx.fillRect(s.x-2.4*view.zoom,s.y-7*view.zoom,4.8*view.zoom,9*view.zoom);ctx.restore()}}
function drawDJ(o){prism(o,16,"#21192e","#100e18","#171321");const b={...o,x:o.x+.15,y:o.y+.38,w:o.w-.3,h:.72};prism(b,46,"#51336e","#261b36","#362148");line(iso(b.x+.1,b.y+b.h,29),iso(b.x+b.w-.1,b.y+b.h,29),COLORS.pink,3,.9);const c=iso(o.x+o.w*.5,o.y+.75,53);ellipse({x:c.x-20,y:c.y},11,5,"#111018");ellipse({x:c.x+20,y:c.y},11,5,"#111018");ellipse({x:c.x-20,y:c.y},4,2,COLORS.pink);ellipse({x:c.x+20,y:c.y},4,2,COLORS.cyan)}
function drawTable(o){const c=iso(o.x+o.w*.5,o.y+o.h*.5,21);ellipse(c,39,17,"#352c46","#b98cff",2,.95);line({x:c.x,y:c.y+5},{x:c.x,y:c.y+29},"#181520",4);[[ -43,7],[43,7],[0,27],[0,-24]].forEach(([dx,dy])=>ellipse({x:c.x+dx,y:c.y+dy},13,6,"#684091"))}
function drawSeat(o){const top=o.style==="luxury"?"#8b4776":o.style==="blue"?"#315f92":o.style==="vip"?"#74418f":"#593a83";prism(o,24,top,"#282039","#38234d");const back={...o,y:o.y-.05,h:Math.min(.35,o.h*.25)};prism(back,o.style==="luxury"?49:43,top,"#2b203d","#3a2552");line(iso(o.x+.1,o.y+o.h,12),iso(o.x+o.w-.1,o.y+o.h,12),o.style==="blue"?COLORS.cyan:COLORS.pink,2,.65)}
function drawDecor(o,time){const c=iso(o.x+.5,o.y+.5);if(o.style==="plant"){const p=worldToScreen(c);rectScreen(p.x-8*view.zoom,p.y-6*view.zoom,16*view.zoom,20*view.zoom,"#2a2033");line(c,{x:c.x-14,y:c.y-36},"#57b879",4);line(c,{x:c.x+13,y:c.y-39},"#57b879",4);line(c,{x:c.x,y:c.y-45},"#57b879",4);return}if(o.style==="speaker"){prism(o,58,"#1d1a24","#0f0e14","#14121a");ellipse(iso(o.x+.52,o.y+.55,38),12,6,"#08070b",COLORS.purple,2);return}if(o.style==="laser"){const q={...o,x:o.x+.34,y:o.y+.34,w:.32,h:.32};prism(q,72,"#3e3256","#191522","#221a2d");ellipse(iso(o.x+.5,o.y+.5,76),7,3,COLORS.cyan,null,1,.7+.3*Math.sin(time*.006));return}if(o.style==="luxury"){prism(o,34,"#6b4e35","#2a211d","#392a23");const p=iso(o.x+o.w*.5,o.y+.55,50);for(let i=-2;i<=2;i++)ellipse({x:p.x+i*9,y:p.y-Math.abs(i)*2},4,2,COLORS.gold);return}ellipse(iso(o.x+.5,o.y+.5,42),15,7,null,COLORS.pink,5,.9);ellipse(iso(o.x+.5,o.y+.5,42),23,11,null,COLORS.cyan,2,.75)}
function drawObject(o,time){if(o.kind==="dance")drawDance(o,time);else if(o.kind==="bar")drawBar(o);else if(o.kind==="dj")drawDJ(o);else if(o.kind==="table")drawTable(o);else if(o.kind==="sofa"||o.kind==="booth")drawSeat(o);else drawDecor(o,time)}
function drawGuest(g,time){const p=iso(g.x,g.y,0),s=worldToScreen(p),bob=g.state==="move"?Math.sin(time*.012+g.phase)*1.7:g.state==="activity"&&g.activity?.kind==="dance"?Math.sin(time*.008+g.phase)*3:0,scale=view.zoom,shirt=g.shirt;ctx.save();ctx.translate(s.x,s.y-bob*scale);ctx.scale(g.flip*scale,scale);ctx.fillStyle="rgba(0,0,0,.27)";ctx.beginPath();ctx.ellipse(0,6,12,4,0,0,Math.PI*2);ctx.fill();if(g.state==="activity"&&g.activity?.kind==="sit"){ctx.strokeStyle="#c9cbd7";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-3,-4);ctx.lineTo(-7,6);ctx.moveTo(3,-4);ctx.lineTo(7,6);ctx.stroke()}else{const gait=g.state==="move"?Math.sin(time*.013+g.phase)*3:0;ctx.strokeStyle="#c9cbd7";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-3,-5);ctx.lineTo(-4-gait*.15,7);ctx.moveTo(3,-5);ctx.lineTo(4+gait*.15,7);ctx.stroke()}ctx.fillStyle=shirt;ctx.beginPath();ctx.roundRect(-8,-32,16,22,5);ctx.fill();ctx.fillStyle=g.skin;ctx.beginPath();ctx.ellipse(0,-43,9,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=g.hair;ctx.beginPath();ctx.ellipse(0,-48,10,5.5,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawPreview(){if(!hoverTile||(!selected&&!bulldoze)||state.open)return;let w=1,h=1,valid=true;if(selected){[w,h]=selected.fp||[1,1];valid=selected.kind==="wall"||canPlace(hoverTile.x,hoverTile.y,w,h)}else valid=hoverTile.x>=0&&hoverTile.y>=0&&hoverTile.x<GRID_W&&hoverTile.y<GRID_H;path(diamond(hoverTile.x,hoverTile.y,w,h,5),bulldoze?"rgba(255,102,127,.22)":valid?"rgba(82,231,255,.22)":"rgba(255,102,127,.22)",bulldoze?COLORS.red:valid?COLORS.cyan:COLORS.red,2)}
function draw(time=performance.now()){ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);drawRoom();const entries=[];objects.forEach(o=>entries.push({d:o.x+o.y+o.w+o.h*.9,type:"o",v:o}));guests.forEach(g=>entries.push({d:g.x+g.y+1.4,type:"g",v:g}));entries.sort((a,b)=>a.d-b.d);for(const e of entries)e.type==="o"?drawObject(e.v,time):drawGuest(e.v,time);drawPreview()}
function blockedSet(){const set=new Set();for(const o of objects)if(o.solid)for(let yy=o.y;yy<o.y+o.h;yy++)for(let xx=o.x;xx<o.x+o.w;xx++)set.add(xx+":"+yy);return set}
function canPlace(x,y,w,h){if(x<0||y<0||x+w>GRID_W||y+h>GRID_H)return false;const b=blockedSet();for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)if(b.has(xx+":"+yy))return false;return true}
function walkable(x,y){return x>=0&&y>=0&&x<GRID_W&&y<GRID_H&&!blockedSet().has(x+":"+y)}
function pathfind(start,goal){const sx=Math.floor(start.x),sy=Math.floor(start.y),gx=Math.floor(goal.x),gy=Math.floor(goal.y);if(!walkable(gx,gy))return[];const key=(x,y)=>x+":"+y,q=[[sx,sy]],came=new Map([[key(sx,sy),null]]),dirs=[[1,0],[-1,0],[0,1],[0,-1]];for(let qi=0;qi<q.length;qi++){const [x,y]=q[qi];if(x===gx&&y===gy)break;for(const [dx,dy]of dirs){const nx=x+dx,ny=y+dy,k=key(nx,ny);if(came.has(k)||!walkable(nx,ny))continue;came.set(k,[x,y]);q.push([nx,ny])}}if(!came.has(key(gx,gy)))return[];const out=[];let cur=[gx,gy];while(cur){out.push({x:cur[0]+.5,y:cur[1]+.5});cur=came.get(key(cur[0],cur[1]))}return out.reverse()}
function approach(o){const arr=[{x:o.x+o.w*.5,y:o.y+o.h+.5},{x:o.x+o.w+.5,y:o.y+o.h*.5},{x:o.x-.5,y:o.y+o.h*.5},{x:o.x+o.w*.5,y:o.y-.5}];return arr.find(p=>walkable(Math.floor(p.x),Math.floor(p.y)))||null}
function chooseActivity(){const opts=[];for(const o of objects){if(o.kind==="dance"){opts.push({kind:"dance",target:{x:o.x+.5+Math.random()*Math.max(0,o.w-1),y:o.y+.5+Math.random()*Math.max(0,o.h-1)},dur:3.5+Math.random()*2.8,spend:10,quality:.62+(o.vibe||0)/180})}else if(o.kind==="bar"){const t=approach(o);if(t)opts.push({kind:"drink",target:t,dur:3+Math.random()*2.2,spend:65+Math.round((o.vibe||0)*.75),quality:.64+(o.vibe||0)/160})}else if(["table","sofa","booth"].includes(o.kind)){const t=approach(o);if(t)opts.push({kind:"sit",target:t,dur:4+Math.random()*2.6,spend:o.kind==="table"?28:38,quality:.61+(o.vibe||0)/170})}}if(!opts.length)return null;const filtered=opts.filter(a=>Math.random()<(a.kind==="drink"?.78:.62)),pool=filtered.length?filtered:opts;return pool[Math.floor(Math.random()*pool.length)]}
